name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Install flow tooling
      run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

    - name: Install deps
      run: go get -v ./...
      
    - name: Test
      run: ./demo.sh
