---
name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Go vet
        run: go vet ./...

      - uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: '-l -d'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
