---
name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - './doc/**'
      - './README.md'
      - 'LICENSE'

jobs:

  emulator:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        env:
          NETWORK: emulator
          RPC_ADDRESS: localhost:3569
          FUNGIBLE_TOKEN_ADDRESS: ee82856bf20e2aa6
          TOKEN_ACCOUNT_ADDRESS: ${{ secrets.EMULATOR_ADDRESS }}
          TOKEN_ACCOUNT_KEYS: ${{ secrets.EMULATOR_KEYS }}
          TOKEN_ACCOUNT_PK: ${{secrets.EMULATOR_PK }}
        run: make test

  testnet:
    if: false
    runs-on: ubuntu-latest
    needs: emulator
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        env:
          NETWORK: testnet
          RPC_ADDRESS: access.devnet.nodes.onflow.org:9000
          FUNGIBLE_TOKEN_ADDRESS: 9a0766d93b6608b7
          TOKEN_ACCOUNT_ADDRESS: ${{ secrets.TESTNET_ADDRESS }}
          TOKEN_ACCOUNT_KEYS: ${{ secrets.TESTNET_KEYS }}
          TOKEN_ACCOUNT_PK: ${{secrets.TESTNET_PK }}
        run: make test
