---
name: Tests

on:
  pull_request:

jobs:

  emulator:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        env:
          NETWORK: emulator
          RPC_ADDRESS: localhost:3569
          FUNGIBLE_TOKEN_ADDRESS: ee82856bf20e2aa6
          OWNER_ADDRESS: 01cf0e2f2f715450
          TESTNET_OWNER: ${{ secrets.TESTNET_OWNER}}
          TESTNET_ALLOWANCE: ${{ secrets.TESTNET_ALLOWANCE}}
          TESTNET_BLOCKLISTER: ${{ secrets.TESTNET_BLOCKLISTER}}
          TESTNET_MINTER: ${{ secrets.TESTNET_MINTER}}
          TESTNET_MINTERCONTROLLER1: ${{ secrets.TESTNET_MINTERCONTROLLER1}}
          TESTNET_MINTERCONTROLLER2: ${{ secrets.TESTNET_MINTERCONTROLLER2}}
          TESTNET_NON_ALLOWANCE: ${{ secrets.TESTNET_NON_ALLOWANCE}}
          TESTNET_NON_BLOCKLISTER: ${{ secrets.TESTNET_NON_BLOCKLISTER}}
          TESTNET_NON_MINTER: ${{ secrets.TESTNET_NON_MINTER}}
          TESTNET_NON_MULTISIG_ACCOUNT: ${{ secrets.TESTNET_NON_MULTISIG_ACCOUNT}}
          TESTNET_NON_PAUSER: ${{ secrets.TESTNET_NON_PAUSER}}
          TESTNET_NON_VAULTED_ACCOUNT: ${{ secrets.TESTNET_NON_VAULTED_ACCOUNT}}
          TESTNET_PAUSER: ${{ secrets.TESTNET_PAUSER}}
          TESTNET_VAULTED_ACCOUNT: ${{ secrets.TESTNET_VAULTED_ACCOUNT}}
          TESTNET_W_1000: ${{ secrets.TESTNET_W_1000}}
          TESTNET_W_500_1: ${{ secrets.TESTNET_W_500_1}}
          TESTNET_W_500_2: ${{ secrets.TESTNET_W_500_2}}
          TESTNET_W_250_1: ${{ secrets.TESTNET_W_250_1}}
          TESTNET_W_250_2: ${{ secrets.TESTNET_W_250_2}}
        run: make test

  # testnet:
  #   runs-on: ubuntu-latest
  #   needs: emulator
  #   timeout-minutes: 60
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16

  #     - name: Test
  #       env:
  #         NETWORK: testnet
  #         RPC_ADDRESS: access.devnet.nodes.onflow.org:9000
  #         FUNGIBLE_TOKEN_ADDRESS: 9a0766d93b6608b7
  #         OWNER_ADDRESS: e722d9815821c8b3
  #         TESTNET_OWNER: ${{ secrets.TESTNET_OWNER}}
  #         TESTNET_ALLOWANCE: ${{ secrets.TESTNET_ALLOWANCE}}
  #         TESTNET_BLOCKLISTER: ${{ secrets.TESTNET_BLOCKLISTER}}
  #         TESTNET_MINTER: ${{ secrets.TESTNET_MINTER}}
  #         TESTNET_MINTERCONTROLLER1: ${{ secrets.TESTNET_MINTERCONTROLLER1}}
  #         TESTNET_MINTERCONTROLLER2: ${{ secrets.TESTNET_MINTERCONTROLLER2}}
  #         TESTNET_NON_ALLOWANCE: ${{ secrets.TESTNET_NON_ALLOWANCE}}
  #         TESTNET_NON_BLOCKLISTER: ${{ secrets.TESTNET_NON_BLOCKLISTER}}
  #         TESTNET_NON_MINTER: ${{ secrets.TESTNET_NON_MINTER}}
  #         TESTNET_NON_MULTISIG_ACCOUNT: ${{ secrets.TESTNET_NON_MULTISIG_ACCOUNT}}
  #         TESTNET_NON_PAUSER: ${{ secrets.TESTNET_NON_PAUSER}}
  #         TESTNET_NON_VAULTED_ACCOUNT: ${{ secrets.TESTNET_NON_VAULTED_ACCOUNT}}
  #         TESTNET_PAUSER: ${{ secrets.TESTNET_PAUSER}}
  #         TESTNET_VAULTED_ACCOUNT: ${{ secrets.TESTNET_VAULTED_ACCOUNT}}
  #         TESTNET_W_1000: ${{ secrets.TESTNET_W_1000}}
  #         TESTNET_W_500_1: ${{ secrets.TESTNET_W_500_1}}
  #         TESTNET_W_500_2: ${{ secrets.TESTNET_W_500_2}}
  #         TESTNET_W_250_1: ${{ secrets.TESTNET_W_250_1}}
  #         TESTNET_W_250_2: ${{ secrets.TESTNET_W_250_2}}
  #       run: make test
